/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Bus")]
    [LuaRegisterType(0x166a3d19b1137d79, typeof(LuaBehaviour))]
    public class Bus : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "c4bb8af5caf943043862b2cbc7e525c2";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Boolean m_returning = false;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Transform> m_travelPoints = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_returning),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_travelPoints),
            };
        }
    }
}

#endif
