/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Database")]
    [LuaRegisterType(0xcc72649256137438, typeof(LuaBehaviour))]
    public class Database : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "a3f9e3064ca71454a9c3f547ee56d761";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<System.String> m_locations = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Texture> m_seasonIcons = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Color> m_seasonColors = default;
        [LuaScriptPropertyAttribute("a2502b0c324894043a57c8e47cac0014")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> m_items = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Texture> m_toolIcons = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_locations),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_seasonIcons),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_seasonColors),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_items),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_toolIcons),
            };
        }
    }
}

#endif
