/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/Item")]
    [LuaRegisterType(0x52cfa1d198476806, typeof(LuaScriptableObject))]
    public class Item : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "a2502b0c324894043a57c8e47cac0014";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_itemName = "";
        [SerializeField] public UnityEngine.Texture m_itemIcon = default;
        [SerializeField] public System.String m_itemType = "";
        [SerializeField] public System.Collections.Generic.List<System.Boolean> m_seasons = default;
        [SerializeField] public System.Collections.Generic.List<System.Boolean> m_locations = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_itemName),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_itemIcon),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_itemType),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_seasons),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_locations),
            };
        }
    }
}

#endif
