/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/NPC_Trigger")]
    [LuaRegisterType(0x86942dfccad2911b, typeof(LuaBehaviour))]
    public class NPC_Trigger : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "5b6a543b8bf594e4bac6905492cdaf62";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_triggerType = "";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_triggerType),
            };
        }
    }
}

#endif
