/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PlotManager")]
    [LuaRegisterType(0xf665fbf0badf1859, typeof(LuaBehaviour))]
    public class PlotManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "8cf33c74c1f705a48be1e60eac242e7e";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("db81b1a43e2ef534fa56e2ec59e659d8")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> m_shops = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_shops),
            };
        }
    }
}

#endif
