/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Plot")]
    [LuaRegisterType(0xcd095719b59ae1e2, typeof(LuaBehaviour))]
    public class Plot : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "db81b1a43e2ef534fa56e2ec59e659d8";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_shopId = 0;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_shopId),
            };
        }
    }
}

#endif
