/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/QuestsManagerModule")]
    [LuaRegisterType(0xc16d32d39deab289, typeof(LuaBehaviour))]
    public class QuestsManagerModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "e90ebeaeab683cf4b9ba3405fc0bc811";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("e68fa88a3d543cc4298ddb651caa4cfb")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> m_generalQuests = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_generalQuests),
            };
        }
    }
}

#endif
