/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/Quest")]
    [LuaRegisterType(0xc74e8775f65e90dd, typeof(LuaScriptableObject))]
    public class Quest : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "e68fa88a3d543cc4298ddb651caa4cfb";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_expReward = 0;
        [SerializeField] public System.String m_description = "";
        [LuaScriptPropertyAttribute("a2502b0c324894043a57c8e47cac0014")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> m_itemsRequired = default;
        [SerializeField] public System.Collections.Generic.List<System.Double> m_itemsCount = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_expReward),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_description),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_itemsRequired),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_itemsCount),
            };
        }
    }
}

#endif
