/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [CreateAssetMenu(menuName = "Highrise/ScriptableObjects/Resource")]
    [LuaRegisterType(0xce39ae3e3f3d3915, typeof(LuaScriptableObject))]
    public class Resource : LuaScriptableObjectThunk
    {
        private const string s_scriptGUID = "f991541301db6dd47b91752d96328df4";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_tool = "";
        [SerializeField] public System.Double m_toolLevel = 0;
        [LuaScriptPropertyAttribute("a2502b0c324894043a57c8e47cac0014")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> m_items = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_tool),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_toolLevel),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_items),
            };
        }
    }
}

#endif
