/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ResourceManagerModule")]
    [LuaRegisterType(0x3ec6346783c5a414, typeof(LuaBehaviour))]
    public class ResourceManagerModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "35f9443521275664796ba8074df78f68";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("b14da0b04d1e59a428097ff6389cef7b")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> m_recourcesTracked = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_recourcesTracked),
            };
        }
    }
}

#endif
