/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/SessionModule")]
    [LuaRegisterType(0x69cfe99b50f24313, typeof(LuaBehaviour))]
    public class SessionModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "6a953acee82d62a4fa32151dc5c3b151";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Material m_seasonMaterial = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Transform> m_travelPoints = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_seasonMaterial),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_travelPoints),
            };
        }
    }
}

#endif
