/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIManagerModule")]
    [LuaRegisterType(0xe3be2f8eee762c6, typeof(LuaBehaviour))]
    public class UIManagerModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "b3e0ec2446d33a44ea97dfcd3e1321cb";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("3f16941e7d562b545a4b7294e8fcd2ac")]
        [SerializeField] public UnityEngine.Object m_hudUI = default;
        [LuaScriptPropertyAttribute("1a1f784b3928a874d9c0caa329c1b24d")]
        [SerializeField] public UnityEngine.Object m_objectInfoUI = default;
        [LuaScriptPropertyAttribute("803fe9b40a68c9748bb029e30e41ee21")]
        [SerializeField] public UnityEngine.Object m_inventoryUI = default;
        [LuaScriptPropertyAttribute("69613151a362b8b44b88c9dc230c2a5a")]
        [SerializeField] public UnityEngine.Object m_busUI = default;
        [LuaScriptPropertyAttribute("1c80658b4281d004cb382d0c410a2684")]
        [SerializeField] public UnityEngine.Object m_itemsLibraryUI = default;
        [LuaScriptPropertyAttribute("da1c5babc6fa43b488da2af2a938e01f")]
        [SerializeField] public UnityEngine.Object m_museumDonationUI = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_hudUI),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_objectInfoUI),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_inventoryUI),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_busUI),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_itemsLibraryUI),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_museumDonationUI),
            };
        }
    }
}

#endif
